### ISSUE TITLE
critcal infos are exported from otel-agent-

### ISSUE THREAD

**Issue by holiday-sunrise** [avioconsulting/mule-opentelemetry-module#229]
Mule Runtime is started with several command args like client_id, client_secret , encryptionkey. How can we filter those data in field "labels.process_command_args"

```
 labels.process_command_args=
/usr/lib64/jvm/temurin-17-jdk/bin/java
......
-Dencryption.key=XXXXXXXX
-Danypoint.platform.client_id=XXXXXXXX
-Danypoint.platform.client_secret=XXXXXXXX
.....
-Dwrapper.key=XXXXXXXX
....
```
security-relevant data should not be in the log

**Comment by holiday-sunrise** [comment]
Any News

**Comment by holiday-sunrise** [comment]
Hi @manikmagar. Thank you for your answer.

Would it be possible to explain to me how I can use the Transformer with a Mule API and the Otel Mule Module. 

Where and how would one create such a transformer.

I would be very happy about your help.

**Comment by manikmagar** [comment]
Hi @holiday-sunrise, the processor and transformer are not for the Otel Mule Module. Those are for [OpenTelemetry collector](https://opentelemetry.io/docs/collector/) configuration. Please see the documentation on the links below -

> Collector Configuration - Use [Resource Processor ](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourceprocessor#resource-processor)in collector configuration to delete process.command_args attribute

>Collector Configuration - If process.command_args are needed but redact certain attribute values, then use [Transform Processor with replace patterns](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor#example) in the collector configuration

Here is an example of deleting the attribute with resource processor -

.OpenTelemetry collector config yaml
```
... any existing configuration ....

processors:
  ... any existing processors ....
  resource/delete_process:
    attributes:
      - key: process.command_args
        action: delete

# Example traces service applying processor on the trace data       
service:
  pipelines:
    traces:
      receivers: [...]
      processors: [resource/delete_process]
      exporters: ....
```

I hope that helps.
